# GitHub Labels Configuration for AI-Whisperers
# Use with: gh label sync --file .github/labels.yml

# Priority Labels
- name: "priority: critical"
  description: "Critical priority - needs immediate attention"
  color: "d73a4a"

- name: "priority: high"
  description: "High priority - should be worked on soon"
  color: "ff6b6b"

- name: "priority: medium"
  description: "Medium priority - normal workflow"
  color: "ffa726"

- name: "priority: low"
  description: "Low priority - can be deferred"
  color: "4fc3f7"

# Type Labels
- name: "type: bug"
  description: "Something isn't working"
  color: "d73a4a"

- name: "type: feature"
  description: "New feature or request"
  color: "a2eeef"

- name: "type: enhancement"
  description: "Improvement to existing feature"
  color: "84c5ff"

- name: "type: documentation"
  description: "Improvements or additions to documentation"
  color: "0075ca"

- name: "type: refactor"
  description: "Code refactoring"
  color: "d4c5f9"

- name: "type: test"
  description: "Adding or updating tests"
  color: "bfe5bf"

- name: "type: chore"
  description: "Maintenance tasks, build updates"
  color: "fef2c0"

# Project Labels
- name: "project: investment-ai"
  description: "Investment AI platform"
  color: "1d76db"

- name: "project: company-website"
  description: "Company website"
  color: "0e8a16"

- name: "project: comment-analyzer"
  description: "Comment analyzer tool"
  color: "5319e7"

- name: "project: core-services"
  description: "Backend services"
  color: "b60205"

- name: "project: ml-models"
  description: "Machine learning models"
  color: "fbca04"

- name: "project: infrastructure"
  description: "Infrastructure and DevOps"
  color: "006b75"

- name: "project: documentation"
  description: "Documentation project"
  color: "c2e0c6"

# Status Labels
- name: "status: needs-triage"
  description: "Needs initial review and prioritization"
  color: "ededed"

- name: "status: blocked"
  description: "Blocked by dependencies or external factors"
  color: "d93f0b"

- name: "status: in-progress"
  description: "Currently being worked on"
  color: "0052cc"

- name: "status: ready-for-review"
  description: "Ready for code review"
  color: "0e8a16"

- name: "status: needs-testing"
  description: "Implementation complete, needs testing"
  color: "f9d0c4"

- name: "status: on-hold"
  description: "Work paused temporarily"
  color: "fef2c0"

# Effort Labels
- name: "effort: xs"
  description: "Extra small - 1-2 hours"
  color: "c5f015"

- name: "effort: s"
  description: "Small - half day"
  color: "7ce38b"

- name: "effort: m"
  description: "Medium - 1-2 days"
  color: "ffa726"

- name: "effort: l"
  description: "Large - 3-5 days"
  color: "ff7043"

- name: "effort: xl"
  description: "Extra large - 1-2 weeks"
  color: "d32f2f"

- name: "effort: xxl"
  description: "Extra extra large - 2+ weeks"
  color: "6a1b9a"

# Special Labels
- name: "good first issue"
  description: "Good for newcomers"
  color: "7057ff"

- name: "help wanted"
  description: "Extra attention is needed"
  color: "008672"

- name: "idea"
  description: "Project or feature idea"
  color: "ff69b4"

- name: "needs-discussion"
  description: "Needs team discussion"
  color: "d876e3"

- name: "duplicate"
  description: "This issue or pull request already exists"
  color: "cfd3d7"

- name: "wontfix"
  description: "This will not be worked on"
  color: "ffffff"

- name: "invalid"
  description: "This doesn't seem right"
  color: "e4e669"

# Business Labels
- name: "business: revenue"
  description: "Directly impacts revenue generation"
  color: "28a745"

- name: "business: growth"
  description: "Supports business growth"
  color: "17a2b8"

- name: "business: operations"
  description: "Internal operations improvement"
  color: "6c757d"

- name: "business: compliance"
  description: "Compliance or legal requirement"
  color: "dc3545"