name: 💡 Project Idea
description: Share a new project or business idea
title: "[IDEA] "
labels: ["idea", "needs-discussion"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Got a great idea for AI-Whisperers? Share it here!

  - type: input
    id: idea-title
    attributes:
      label: Idea Title
      description: A catchy name for your idea
      placeholder: "AI-Powered Social Media Scheduler"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What type of project is this?
      options:
        - AI/ML Application
        - Web Platform
        - Mobile App
        - API Service
        - Tool/Utility
        - Integration
        - Research Project
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Idea Description
      description: Describe your idea in detail
      placeholder: "This project would..."
    validations:
      required: true

  - type: textarea
    id: target-audience
    attributes:
      label: Target Audience
      description: Who would use this?
      placeholder: "This would be useful for..."
    validations:
      required: true

  - type: textarea
    id: value-proposition
    attributes:
      label: Value Proposition
      description: What problem does this solve? What's the benefit?
      placeholder: "This solves the problem of..."
    validations:
      required: true

  - type: textarea
    id: technical-approach
    attributes:
      label: Technical Approach
      description: How might this be built? What technologies?
      placeholder: "Could be built using..."
    validations:
      required: false

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this would be?
      options:
        - Simple - Weekend project
        - Medium - 2-4 weeks
        - Complex - 1-3 months
        - Major - 3+ months
        - Unsure
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Business Priority
      description: How important is this for AI-Whisperers?
      options:
        - Low - Interesting but not urgent
        - Medium - Good addition to portfolio
        - High - Could be a key product
        - Critical - Must-have for business growth
    validations:
      required: true

  - type: textarea
    id: additional-thoughts
    attributes:
      label: Additional Thoughts
      description: Any other details, references, or inspiration?
      placeholder: "Also worth considering..."
    validations:
      required: false